### ISSUE TITLE
Finetuning

### ISSUE THREAD

**Issue by TreyWi** [ThomasLamsonFr/AITextGenerator#10]
Every time I try to restart finetuning from an epoch or save state it errors out on memory. Did you try and restart finetuning when you build this script?

**Comment by TreyWi** [comment]
File "finetuning.py", line 840, in <module>
    main()
  File "finetuning.py", line 790, in main
    global_step, tr_loss = train(args, train_dataset, model, tokenizer)
  File "finetuning.py", line 354, in train
    outputs = model(input_ids, labels=labels, token_type_ids=type_ids)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/opt/conda/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/apex/amp/_initialize.py", line 197, in new_fwd
    **applier(kwargs, input_caster))
  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_gpt2.py", line 599, in forward
    inputs_embeds=inputs_embeds,
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_gpt2.py", line 465, in forward
    inputs_embeds = self.wte(input_ids)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py", line 1724, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: arguments are located on different GPUs at /pytorch/aten/src/THC/generic/THCTensorIndex.cu:403

**Comment by ThomasLamsonFr** [comment]
Hello,
I'm sorry but we never encountered this kind of error, and yes we did restart finetuning from checkpoints a few times. On the memory aspect of it, it is known to us that running the finetuning script (with any options) requires lots of it, but with a small batch size (2) it's supposed to run fine on 8Go RAM NVidia graphics cards.

We could only run bigger batches on Nvidia Tesla on AWS and Google Cloud.

However, it seems the traceback you're posting is not directly related to memory, as your original post states. Do you have more details on the conditions of its occurence?

What kind of device are you using, does it have multiple GPUs, and were you able to run a few epochs without restarting?

**Comment by TreyWi** [comment]
I just ported from colab to running it on GCP, I tried to not bother figuring out the memory issue by throwing more GPU's at the problem and got that error, now that you pointed it out its not related to one another, it evidently is having issues keeping the two GPU's in sync (Still need to track that down this week). The CUDA error bombs out no matter where I restart (I ran a job where it stopped saving at 20k in GCP so I tried restarting backwards from there, I didn't try any smaller than 1000 but it still had an error on 1000. It got to about 500 iterations at the 20000 save and I saved a copy of the 4000 attempt.


04/15/2021 19:55:43 - INFO - __main__ -   ***** Running training *****
04/15/2021 19:55:43 - INFO - __main__ -     Num examples = 5070
04/15/2021 19:55:43 - INFO - __main__ -     Num Epochs = 5
04/15/2021 19:55:43 - INFO - __main__ -     Instantaneous batch size per GPU = 1
04/15/2021 19:55:43 - INFO - __main__ -     Total train batch size (w. parallel, distributed & accumulation) = 5
04/15/2021 19:55:43 - INFO - __main__ -     Gradient Accumulation steps = 5
04/15/2021 19:55:43 - INFO - __main__ -     Total optimization steps = 5070
04/15/2021 19:55:43 - INFO - __main__ -     Continuing training from checkpoint, will skip to saved global_step
04/15/2021 19:55:43 - INFO - __main__ -     Continuing training from epoch 3
04/15/2021 19:55:43 - INFO - __main__ -     Continuing training from global step 4000
04/15/2021 19:55:43 - INFO - __main__ -     Will skip the first 958 steps in the first epoch
Epoch:   0% 0/2 [00:00<?, ?it/s]
Iteration:   0% 0/5070 [00:00<?, ?it/s]
Iteration:   0% 9/5070 [00:00<00:58, 86.10it/s]
Iteration:   0% 19/5070 [00:00<00:56, 88.81it/s]
Iteration:   1% 31/5070 [00:00<00:52, 95.97it/s]
Iteration:   1% 44/5070 [00:00<00:49, 101.45it/s]
Iteration:   1% 56/5070 [00:00<00:47, 106.21it/s]
Iteration:   1% 69/5070 [00:00<00:44, 111.24it/s]
Iteration:   2% 82/5070 [00:00<00:43, 114.76it/s]
Iteration:   2% 96/5070 [00:00<00:41, 119.56it/s]
Iteration:   2% 109/5070 [00:00<00:41, 119.90it/s]
Iteration:   2% 123/5070 [00:01<00:40, 123.22it/s]
Iteration:   3% 138/5070 [00:01<00:38, 129.23it/s]
Iteration:   3% 151/5070 [00:01<00:38, 128.99it/s]
Iteration:   3% 167/5070 [00:01<00:36, 134.90it/s]
Iteration:   4% 185/5070 [00:01<00:33, 143.94it/s]
Iteration:   4% 200/5070 [00:01<00:34, 139.44it/s]
Iteration:   4% 215/5070 [00:01<00:35, 138.66it/s]
Iteration:   5% 229/5070 [00:01<00:35, 135.64it/s]
Iteration:   5% 245/5070 [00:01<00:34, 140.78it/s]
Iteration:   5% 260/5070 [00:02<00:34, 141.15it/s]
Iteration:   5% 275/5070 [00:02<00:33, 141.33it/s]
Iteration:   6% 292/5070 [00:02<00:32, 146.07it/s]
Iteration:   6% 310/5070 [00:02<00:31, 151.97it/s]
Iteration:   6% 326/5070 [00:02<00:31, 149.95it/s]
Iteration:   7% 342/5070 [00:02<00:31, 152.23it/s]
Iteration:   7% 359/5070 [00:02<00:30, 154.78it/s]
Iteration:   7% 375/5070 [00:02<00:30, 151.50it/s]
Iteration:   8% 391/5070 [00:02<00:31, 150.89it/s]
Iteration:   8% 407/5070 [00:02<00:30, 151.50it/s]
Iteration:   8% 423/5070 [00:03<00:30, 153.26it/s]
Iteration:   9% 439/5070 [00:03<00:30, 153.57it/s]
Iteration:   9% 456/5070 [00:03<00:29, 155.68it/s]
Iteration:   9% 473/5070 [00:03<00:28, 159.67it/s]
Iteration:  10% 490/5070 [00:03<00:28, 159.95it/s]
Iteration:  10% 507/5070 [00:03<00:28, 158.21it/s]
Iteration:  10% 523/5070 [00:03<00:28, 157.91it/s]
Iteration:  11% 539/5070 [00:03<00:28, 157.35it/s]
Iteration:  11% 556/5070 [00:03<00:28, 160.25it/s]
Iteration:  11% 574/5070 [00:04<00:27, 163.91it/s]
Iteration:  12% 591/5070 [00:04<00:27, 162.50it/s]
Iteration:  12% 608/5070 [00:04<00:27, 164.06it/s]
Iteration:  12% 625/5070 [00:04<00:27, 162.30it/s]
Iteration:  13% 643/5070 [00:04<00:26, 166.06it/s]
Iteration:  13% 660/5070 [00:04<00:26, 165.65it/s]
Iteration:  13% 678/5070 [00:04<00:25, 169.43it/s]
Iteration:  14% 695/5070 [00:04<00:26, 164.84it/s]
Iteration:  14% 715/5070 [00:04<00:25, 173.73it/s]
Iteration:  14% 734/5070 [00:04<00:24, 175.00it/s]
Iteration:  15% 752/5070 [00:05<00:25, 170.01it/s]
Iteration:  15% 770/5070 [00:05<00:24, 172.26it/s]
Iteration:  16% 788/5070 [00:05<00:24, 171.67it/s]
Iteration:  16% 806/5070 [00:05<00:25, 166.57it/s]
Iteration:  16% 823/5070 [00:05<00:25, 167.36it/s]
Iteration:  17% 841/5070 [00:05<00:24, 169.54it/s]
Iteration:  17% 858/5070 [00:05<00:25, 165.55it/s]
Iteration:  17% 876/5070 [00:05<00:24, 168.63it/s]
Iteration:  18% 895/5070 [00:05<00:24, 171.45it/s]
Iteration:  18% 913/5070 [00:06<00:24, 171.37it/s]
Iteration:  18% 931/5070 [00:06<00:24, 171.30it/s]
Iteration:  19% 949/5070 [00:06<00:23, 172.41it/s]/pytorch/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of add_ is deprecated:
	add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
	add_(Tensor other, *, Number alpha)

Iteration:  19% 967/5070 [00:08<03:03, 22.37it/s] 
Iteration:  19% 980/5070 [00:11<06:48, 10.02it/s]
Iteration:  20% 989/5070 [00:13<08:41,  7.83it/s]Traceback (most recent call last):
  File "finetuning.py", line 838, in <module>
    main()
  File "finetuning.py", line 788, in main
    global_step, tr_loss = train(args, train_dataset, model, tokenizer)
  File "finetuning.py", line 362, in train
    scaled_loss.backward()
  File "/usr/local/lib/python3.7/dist-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 194.00 MiB (GPU 0; 15.78 GiB total capacity; 13.94 GiB already allocated; 154.75 MiB free; 14.47 GiB reserved in total by PyTorch) (malloc at /pytorch/c10/cuda/CUDACachingAllocator.cpp:289)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7f698eb62536 in /usr/local/lib/python3.7/dist-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1cf1e (0x7f698edabf1e in /usr/local/lib/python3.7/dist-packages/torch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x1df9e (0x7f698edacf9e in /usr/local/lib/python3.7/dist-packages/torch/lib/libc10_cuda.so)
frame #3: THCStorage_resize + 0x96 (0x7f6990033186 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_cuda.so)
frame #4: THCTensor_resizeNd + 0x441 (0x7f6990044341 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_cuda.so)
frame #5: THNN_CudaClassNLLCriterion_updateGradInput + 0x6a (0x7f69908e7d9a in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0x1020888 (0x7f698ffde888 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0xfa4a2b (0x7f698ff62a2b in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_cuda.so)
frame #8: <unknown function> + 0x10c4b13 (0x7f69cc50cb13 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0x2b49658 (0x7f69cdf91658 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_cpu.so)
frame #10: <unknown function> + 0x10c4b13 (0x7f69cc50cb13 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_cpu.so)
frame #11: torch::autograd::generated::NllLossBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x276 (0x7f69cdcecdb6 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0x2d89c05 (0x7f69ce1d1c05 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_cpu.so)
frame #13: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x16f3 (0x7f69ce1cef03 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_cpu.so)
frame #14: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x3d2 (0x7f69ce1cfce2 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_cpu.so)
frame #15: torch::autograd::Engine::thread_init(int) + 0x39 (0x7f69ce1c8359 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_cpu.so)
frame #16: torch::autograd::python::PythonEngine::thread_init(int) + 0x38 (0x7f69da907998 in /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_python.so)
frame #17: <unknown function> + 0xbd6df (0x7f69fcb686df in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #18: <unknown function> + 0x76db (0x7f69fe03b6db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #19: clone + 0x3f (0x7f69fd17071f in /lib/x86_64-linux-gnu/libc.so.6)


Epoch:   0% 0/2 [00:14<?, ?it/s]
Iteration:  20% 989/5070 [00:14<01:00, 67.84it/s]

**Comment by Mick-crypto** [comment]
Any luck? I've run into the same issue with this project

**Comment by TreyWi** [comment]
I'm currently experimenting with upgrading Tensor but I've run out of time to do it this week.
